#!/usr/bin/env python3
"""Build and wirelessly install ESPHome on a Petkit Fresh Element Mini."""

from __future__ import annotations

import argparse
import base64
from datetime import datetime
import getpass
import json
import os
from pathlib import Path
import secrets
import shutil
import socket
import subprocess
import sys
import time
import urllib.parse


REPOSITORIES = {
    "petkit-compat-server": "https://github.com/wrobelda/petkit-compat-server.git",
    "esphome-kickstart": "https://github.com/wrobelda/esphome-kickstart.git",
}
ALLOWED_REPOSITORY_ORIGINS = {
    "petkit-compat-server": {"wrobelda/petkit-compat-server"},
    "esphome-kickstart": {
        "libretiny-eu/esphome-kickstart",
        "wrobelda/esphome-kickstart",
    },
}
REPOSITORY_MARKERS = {
    "petkit-compat-server": ("serve_petkit_api.py", "provision_petkit_device.py"),
    "esphome-kickstart": (
        "components/esp8266_nonos_v2_to_eboot_v1/__init__.py",
        "tools/build_esp8266_nonos_v2.py",
    ),
}
PROFILE = Path("devices/esp8266/nonos_v2/fresh-element-mini/profile.json")
PLACEHOLDER_SECRETS = {
    "wifi_ssid": "YourWiFi",
    "wifi_password": "YourWiFiPassword",
    "fallback_ap_password": "ChangeThisAPPassword",
    "kickstart_web_password": "ChangeThisWebPassword",
    "api_key": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",
}


def run(command: list[str], *, cwd: Path, env: dict[str, str] | None = None) -> None:
    print(f"\n+ {' '.join(command)}")
    subprocess.run(command, cwd=cwd, env=env, check=True)


def run_authenticated_curl(
    arguments: list[str], *, username: str, password: str, cwd: Path
) -> None:
    def quote(value: str) -> str:
        return value.replace("\\", "\\\\").replace('"', '\\"')

    command = ["curl", "--config", "-", "--digest", "--fail-with-body", *arguments]
    print(f"\n+ curl --config - {' '.join(command[3:])}")
    subprocess.run(
        command,
        cwd=cwd,
        input=f'user = "{quote(username)}:{quote(password)}"\n',
        text=True,
        check=True,
    )


def download_recovery(
    path: Path, *, url: str, username: str, password: str, cwd: Path
) -> None:
    descriptor = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    os.close(descriptor)
    try:
        run_authenticated_curl(
            ["--output", str(path), url],
            username=username,
            password=password,
            cwd=cwd,
        )
        path.chmod(0o600)
    except BaseException:
        path.unlink(missing_ok=True)
        raise


def prompt(label: str, default: str | None = None, *, secret: bool = False) -> str:
    suffix = f" [{default}]" if default else ""
    reader = getpass.getpass if secret else input
    while True:
        value = reader(f"{label}{suffix}: ").strip()
        if value:
            return value
        if default is not None:
            return default


def yaml_string(value: str) -> str:
    return json.dumps(value)


def read_simple_secrets(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or ":" not in line:
            continue
        key, raw_value = line.split(":", 1)
        raw_value = raw_value.strip()
        if len(raw_value) >= 2 and raw_value.startswith("'") and raw_value.endswith("'"):
            value = raw_value[1:-1].replace("''", "'")
        else:
            try:
                value = json.loads(raw_value)
            except json.JSONDecodeError:
                value = raw_value
        if isinstance(value, str):
            values[key.strip()] = value
    return values


def write_secrets(path: Path) -> dict[str, str]:
    values = {
        "wifi_ssid": prompt("2.4 GHz Wi-Fi network name"),
        "wifi_password": prompt("Wi-Fi password", secret=True),
        "fallback_ap_password": prompt(
            "Fallback access-point password", secrets.token_urlsafe(12)
        ),
        "kickstart_web_username": prompt("Kickstart web username", "admin"),
        "kickstart_web_password": prompt(
            "Kickstart web password", secrets.token_urlsafe(16)
        ),
        "api_key": base64.b64encode(secrets.token_bytes(32)).decode("ascii"),
    }
    path.write_text(
        "# Generated by install.py. Do not commit this file.\n"
        + "".join(f"{key}: {yaml_string(value)}\n" for key, value in values.items()),
        encoding="utf-8",
    )
    path.chmod(0o600)
    return values


def load_or_create_secrets(path: Path) -> dict[str, str]:
    if path.exists():
        values = read_simple_secrets(path)
        path.chmod(0o600)
        print(f"Using existing {path}")
        return values
    return write_secrets(path)


def detect_timezone() -> str:
    localtime = Path("/etc/localtime")
    try:
        target = localtime.resolve()
        marker = "/zoneinfo/"
        if marker in str(target):
            return str(target).split(marker, 1)[1]
    except OSError:
        pass
    return os.environ.get("TZ", "UTC")


def detect_local_ip() -> str:
    with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as sock:
        sock.connect(("192.0.2.1", 9))
        return str(sock.getsockname()[0])


def wait_for_host(host: str, port: int, timeout: int = 180) -> str:
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        try:
            address = socket.gethostbyname(host)
            with socket.create_connection((address, port), timeout=2):
                return address
        except OSError:
            time.sleep(2)
    raise RuntimeError(f"{host}:{port} did not become reachable within {timeout} seconds")


def require_build_artifact(path: Path, description: str) -> None:
    if not path.is_file() or path.stat().st_size == 0:
        raise RuntimeError(f"{description} was not created at {path}")


def github_repository(url: str) -> str | None:
    if url.startswith("git@github.com:"):
        path = url.removeprefix("git@github.com:")
    else:
        parsed = urllib.parse.urlsplit(url)
        if parsed.hostname != "github.com":
            return None
        path = parsed.path.lstrip("/")
    return path.removesuffix(".git").rstrip("/")


def validate_checkout(path: Path, name: str) -> None:
    if not (path / ".git").exists():
        raise RuntimeError(f"{path} exists but is not a Git checkout")
    try:
        origin = subprocess.run(
            ["git", "remote", "get-url", "origin"],
            cwd=path,
            check=True,
            capture_output=True,
            text=True,
        ).stdout.strip()
    except subprocess.CalledProcessError as error:
        raise RuntimeError(f"{path} has no readable origin remote") from error
    repository = github_repository(origin)
    if repository not in ALLOWED_REPOSITORY_ORIGINS[name]:
        expected = ", ".join(sorted(ALLOWED_REPOSITORY_ORIGINS[name]))
        raise RuntimeError(
            f"{path} has unexpected origin {origin!r}; expected {expected}"
        )
    missing = [marker for marker in REPOSITORY_MARKERS[name] if not (path / marker).is_file()]
    if missing:
        raise RuntimeError(f"{path} is missing required files: {', '.join(missing)}")


def ensure_checkout(parent: Path, name: str, url: str) -> Path:
    path = parent / name
    if path.is_dir():
        validate_checkout(path, name)
        return path
    run(["git", "clone", url, name], cwd=parent)
    validate_checkout(path, name)
    return path


def configure_firewall() -> bool:
    if shutil.which("firewall-cmd") is None:
        return False
    query = subprocess.run(
        ["firewall-cmd", "--query-port=8080/tcp"], capture_output=True, check=False
    )
    if query.returncode == 0:
        return False
    answer = input("Temporarily allow TCP port 8080 through firewalld? [Y/n]: ").strip()
    if answer.lower() not in {"", "y", "yes"}:
        return False
    subprocess.run(
        ["sudo", "firewall-cmd", "--add-port=8080/tcp"], check=True
    )
    return True


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--kickstart-host",
        default="petkit-kickstart.local",
        help="Kickstart hostname or IP address",
    )
    args = parser.parse_args()

    project = Path(__file__).resolve().parent
    parent = project.parent
    compat = ensure_checkout(parent, "petkit-compat-server", REPOSITORIES["petkit-compat-server"])
    kickstart = ensure_checkout(parent, "esphome-kickstart", REPOSITORIES["esphome-kickstart"])
    if shutil.which("curl") is None:
        raise SystemExit("curl is required for the authenticated migration upload")

    venv = project / ".venv"
    if not venv.exists():
        run([sys.executable, "-m", "venv", str(venv)], cwd=project)
    python = venv / "bin" / "python"
    esphome = venv / "bin" / "esphome"
    run([str(python), "-m", "pip", "install", "esphome==2026.9.0b1"], cwd=project)

    secrets_path = project / "esphome" / "secrets.yaml"
    values = load_or_create_secrets(secrets_path)
    required = {
        "wifi_ssid",
        "wifi_password",
        "fallback_ap_password",
        "kickstart_web_username",
        "kickstart_web_password",
        "api_key",
    }
    missing = sorted(required - values.keys())
    if missing:
        raise SystemExit(f"{secrets_path} is missing: {', '.join(missing)}")
    placeholders = sorted(
        key for key, placeholder in PLACEHOLDER_SECRETS.items() if values[key] == placeholder
    )
    if placeholders:
        raise SystemExit(
            f"{secrets_path} still contains example values for: "
            f"{', '.join(placeholders)}"
        )

    build_env = os.environ.copy()
    build_env["KICKSTART_COMPONENTS_PATH"] = str((kickstart / "components").resolve())
    run([str(esphome), "compile", "petkit-kickstart.yaml"], cwd=project / "esphome", env=build_env)
    run([str(esphome), "compile", "petkit-feeder.yaml"], cwd=project / "esphome", env=build_env)

    release = project / "local-cache" / "release"
    release.mkdir(parents=True, exist_ok=True)
    transition = release / "petkit-element-mini-kickstart-v2.bin"
    transition_elf = (
        project
        / "esphome/.esphome/build/petkit-kickstart/.pioenvs/petkit-kickstart/firmware.elf"
    )
    factory = (
        project
        / "esphome/.esphome/build/petkit-feeder/.pioenvs/petkit-feeder/firmware.factory.bin"
    )
    require_build_artifact(transition_elf, "Kickstart ELF")
    require_build_artifact(factory, "final ESPHome factory image")
    run(
        [
            str(python),
            str(kickstart / "tools/build_esp8266_nonos_v2.py"),
            "--irom-vma",
            "0x40201010",
            "--entry-symbol",
            "app_entry",
            "--max-size",
            "0x0fa000",
            "--flash-mode",
            "qio",
            "--flash-frequency",
            "40m",
            "--flash-layout",
            "2MB-c1",
            str(transition_elf),
            str(transition),
        ],
        cwd=project,
    )

    computer_ip = prompt("This computer's address on the target Wi-Fi", detect_local_ip())
    timezone_name = prompt("IANA time zone", detect_timezone())
    offset = datetime.now().astimezone().utcoffset()
    timezone_offset = str((offset.total_seconds() if offset else 0) / 3600)
    firewall_added = configure_firewall()
    server = subprocess.Popen(
        [
            str(python),
            "serve_petkit_api.py",
            "--host",
            "0.0.0.0",
            "--port",
            "8080",
            "--profile",
            str(PROFILE),
            "--ota-image",
            str(transition),
        ],
        cwd=compat,
    )
    try:
        time.sleep(1)
        if server.poll() is not None:
            raise RuntimeError("the local Petkit API server did not start")
        input(
            "\nPut the feeder in setup mode, connect this computer to its "
            "PETKIT_FEEDER_... Wi-Fi network, then press Enter."
        )
        provision_env = os.environ.copy()
        provision_env["ESPHOME_WIFI_PASSWORD"] = values["wifi_password"]
        run(
            [
                str(python),
                "provision_petkit_device.py",
                "--profile",
                str(PROFILE),
                "--ssid",
                values["wifi_ssid"],
                "--server",
                f"http://{computer_ip}:8080/6/",
                "--timezone",
                timezone_offset,
                "--locale",
                timezone_name,
                "--send",
            ],
            cwd=compat,
            env=provision_env,
        )
        input(
            "\nReconnect this computer to the target Wi-Fi network. Wait for "
            "the feeder to install Kickstart, then press Enter."
        )
        kickstart_ip = wait_for_host(args.kickstart_host, 80)
        print(f"Kickstart is reachable at {kickstart_ip}")

        recovery = release / f"petkit-post-kickstart-{int(time.time())}.bin"
        download_recovery(
            recovery,
            url=f"http://{kickstart_ip}/hub/flash_read",
            username=values["kickstart_web_username"],
            password=values["kickstart_web_password"],
            cwd=project,
        )
        if recovery.stat().st_size != 0x200000:
            raise RuntimeError("Kickstart recovery download is not 2 MiB")
        run_authenticated_curl(
            [
                "--form",
                f"firmware=@{factory}",
                f"http://{kickstart_ip}/hub/migrate?confirm=replace-vendor-bootloader",
            ],
            username=values["kickstart_web_username"],
            password=values["kickstart_web_password"],
            cwd=project,
        )
        print(f"\nMigration accepted. Keep the recovery image at {recovery}.")
    finally:
        server.terminate()
        try:
            server.wait(timeout=5)
        except subprocess.TimeoutExpired:
            server.kill()
        if firewall_added:
            subprocess.run(
                ["sudo", "firewall-cmd", "--remove-port=8080/tcp"], check=False
            )


if __name__ == "__main__":
    main()
